version: '3.8'

services:

  gps-microservice:
    image: gps-microservice
    container_name: gps-microservice
    build:
      context: gpsMicroservice
      dockerfile: Dockerfile
    ports:
      - "9091:9091"
    networks:
      - web-server-bridge
    restart: always

  rewards-microservice:
    image: rewards-microservice
    container_name: rewards-microservice
    build:
      context: rewardsMicroservice
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    depends_on:
      - gps-microservice
    networks:
      - web-server-bridge
    restart: always

  tripdeals-microservice:
    image: tripdeals-microservice
    container_name: tripdeals-microservice
    build:
      context: tripDealsMicroservice
      dockerfile: Dockerfile
    ports:
      - "9093:9093"
    networks:
      - web-server-bridge
    restart: always

  tourguide:
    environment:
      - CLIENT_GPS_BASE_URL=http://gps-microservice:9091/gps
      - CLIENT_REWARDS_BASE_URL=http://rewards-microservice:9092/rewards
      - CLIENT_TRIPDEALS_BASE_URL=http://tripdeals-microservice:9093/tripDeals
    image: tourguide
    container_name: tourguide
    ports:
      - "9090:9090"
    build:
      context: tourGuide
      dockerfile: Dockerfile
    depends_on:
      - gps-microservice
      - rewards-microservice
      - tripdeals-microservice
    networks:
      - web-server-bridge
    restart: always
    # restart: unless-stopped
    # stdin_open: true

networks:
  web-server-bridge:
    driver: bridge
